print("Hello World")
print("What is your name?")
name = input('>')
print('It is good to meet you ' + name)
print('The length of your name is: ', len(name))
print('What is your name?')
age = input('>')
print('You will be ' + str(int(age)+1) + 'in a year.')